// swift-tools-version:5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription

let package = Package(
    name: "MTTransitions",
    platforms: [.iOS(.v16)],
    products: [.library(name: "MTTransitions",
                        targets: ["MTTransitions"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
         .package(url: "https://github.com/MetalPetal/MetalPetal", from: "1.24.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "MTTransitions",
            dependencies: ["MetalPetal"],
            path: "Source",
            exclude: [
                "Transitions/MTAngularTransition.metal",
                "Transitions/MTBookFlipTransition.metal",
                "Transitions/MTBounceTransition.metal",
                "Transitions/MTBowTieHorizontalTransition.metal",
                "Transitions/MTBowTieVerticalTransition.metal",
                "Transitions/MTBurnTransition.metal",
                "Transitions/MTButterflyWaveScrawlerTransition.metal",
                "Transitions/MTCannabisleafTransition.metal",
                "Transitions/MTCircleCropTransition.metal",
                "Transitions/MTCircleOpenTransition.metal",
                "Transitions/MTCircleTransition.metal",
                "Transitions/MTColorPhaseTransition.metal",
                "Transitions/MTColourDistanceTransition.metal",
                "Transitions/MTCoordFromInTransition.metal",
                "Transitions/MTCrazyParametricFunTransition.metal",
                "Transitions/MTCrossHatchTransition.metal",
                "Transitions/MTCrossWarpTransition.metal",
                "Transitions/MTCrossZoomTransition.metal",
                "Transitions/MTCubeTransition.metal",
                "Transitions/MTDirectionalEasingTransition.metal",
                "Transitions/MTDirectionalTransition.metal",
                "Transitions/MTDirectionalWarpTransition.metal",
                "Transitions/MTDirectionalWipeTransition.metal",
                "Transitions/MTDisplacementTransition.metal",
                "Transitions/MTDissolveTransition.metal",
                "Transitions/MTDoomScreenTransition.metal",
                "Transitions/MTDoorwayTransition.metal",
                "Transitions/MTDreamyTransition.metal",
                "Transitions/MTDreamyZoomTransition.metal",
                "Transitions/MTFadeColorTransition.metal",
                "Transitions/MTFadegrayscaleTransition.metal",
                "Transitions/MTFadeInWipeLeftTransition.metal",
                "Transitions/MTFadeInWipeUpTransition.metal",
                "Transitions/MTFadeTransition.metal",
                "Transitions/MTFlyeyeTransition.metal",
                "Transitions/MTGlitchDisplaceTransition.metal",
                "Transitions/MTGlitchMemoriesTransition.metal",
                "Transitions/MTGridFlipTransition.metal",
                "Transitions/MTHeartTransition.metal",
                "Transitions/MTHexagonalizeTransition.metal",
                "Transitions/MTInvertedPageCurlTransition.metal",
                "Transitions/MTKaleidoScopeTransition.metal",
                "Transitions/MTLeftRightTransition.metal",
                "Transitions/MTLinearBlurTransition.metal",
                "Transitions/MTLissajousTilesTransition.metal",
                "Transitions/MTLumaTransition.metal",
                "Transitions/MTLuminanceMeltTransition.metal",
                "Transitions/MTMorphTransition.metal",
                "Transitions/MTMosaicTransition.metal",
                "Transitions/MTMosaicYueDevTransition.metal",
                "Transitions/MTMultiplyBlendTransition.metal",
                "Transitions/MTOverexposureTransition.metal",
                "Transitions/MTParametricGlitchTransition.metal",
                "Transitions/MTPerlinTransition.metal",
                "Transitions/MTPinwheelTransition.metal",
                "Transitions/MTPixelizeTransition.metal",
                "Transitions/MTPolarFunctionTransition.metal",
                "Transitions/MTPolkaDotsCurtainTransition.metal",
                "Transitions/MTPowerKaleidoTransition.metal",
                "Transitions/MTRadialTransition.metal",
                "Transitions/MTRandomNoisexTransition.metal",
                "Transitions/MTRandomSquaresTransition.metal",
                "Transitions/MTRippleTransition.metal",
                "Transitions/MTRotateScaleFadeTransition.metal",
                "Transitions/MTRotateTransition.metal",
                "Transitions/MTScaleInTransition.metal",
                "Transitions/MTSimpleZoomTransition.metal",
                "Transitions/MTSquaresWireTransition.metal",
                "Transitions/MTSqueezeTransition.metal",
                "Transitions/MTStarWipeTransition.metal",
                "Transitions/MTStaticFadeTransition.metal",
                "Transitions/MTStereoViewerTransition.metal",
                "Transitions/MTSwapTransition.metal",
                "Transitions/MTSwirlTransition.metal",
                "Transitions/MTTangentMotionBlurTransition.metal",
                "Transitions/MTTopBottomTransition.metal",
                "Transitions/MTTVStaticTransition.metal",
                "Transitions/MTUndulatingBurnOutTransition.metal",
                "Transitions/MTWaterDropTransition.metal",
                "Transitions/MTWindowBlindsTransition.metal",
                "Transitions/MTWindowSliceTransition.metal",
                "Transitions/MTWindTransition.metal",
                "Transitions/MTWipeDownTransition.metal",
                "Transitions/MTWipeLeftTransition.metal",
                "Transitions/MTWipeRightTransition.metal",
                "Transitions/MTWipeUpTransition.metal",
                "Transitions/MTZoomInCirclesTransition.metal"
            ],
            resources: [
                // Copy pre-compiled .metallib files and exclude .metal files.
                // Some .metal files contain #include "MTIShaderLib.h", which prevents us from using `.process`.
                // Therefore, we precompile them instead.
                .copy("Resources/Shaders"),
                .copy("Assets.bundle")
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)
